package com.app.winterarc.demo;

import com.app.winterarc.core.time.TimeProvider;
import com.app.winterarc.data.db.Mappers;
import com.app.winterarc.data.db.WinterArcDatabase;
import com.app.winterarc.data.db.entity.MilestoneEntity;
import com.app.winterarc.data.db.entity.ProgressEntryEntity;
import com.app.winterarc.domain.engine.ProgressionEngine;
import com.app.winterarc.domain.model.ActivityType;
import com.app.winterarc.domain.model.Amount;
import com.app.winterarc.domain.model.CelebrationState;
import com.app.winterarc.domain.model.EntryStatus;
import com.app.winterarc.domain.model.Goal;
import com.app.winterarc.domain.model.GoalColor;
import com.app.winterarc.domain.model.GoalIcon;
import com.app.winterarc.domain.model.GoalStatus;
import com.app.winterarc.domain.model.GoalUnit;
import com.app.winterarc.domain.model.ProgressionPlan;
import com.app.winterarc.domain.model.ReminderConfig;
import com.app.winterarc.domain.model.SkipReason;
import com.app.winterarc.domain.model.TrackingMode;
import com.app.winterarc.domain.model.WeeklySchedule;
import com.app.winterarc.domain.repository.ReminderScheduler;

import java.time.DayOfWeek;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Random;
import java.util.UUID;

import javax.inject.Inject;

/**
 * Debug-only demo scenario (this file lives in src/debug and is absent from release builds).
 *
 * <ul>
 *   <li>Morning Walk: 5-month consistency history with a live streak.</li>
 *   <li>Road to 10K: a progression one completion away from its final milestone; today is a
 *       scheduled day, so checking in triggers the milestone celebration.</li>
 *   <li>Read 20 pages: weekday consistency goal.</li>
 *   <li>Meditation 5 to 30 min: a progression mid-way.</li>
 *   <li>Couch to 5K: a completed, archived progression.</li>
 * </ul>
 *
 * Progression histories are generated by the same rules the app uses: a target advances by one
 * hop only on a completed day.
 */
public class DebugDemoTools implements DemoTools {
    private final WinterArcDatabase db;
    private final TimeProvider time;
    private final ReminderScheduler reminders;

    @Inject
    public DebugDemoTools(WinterArcDatabase db, TimeProvider time, ReminderScheduler reminders) {
        this.db = db;
        this.time = time;
        this.reminders = reminders;
    }

    @Override
    public boolean isAvailable() {
        return true;
    }

    @Override
    public void clearAllData() {
        for (Goal g : Mappers.mapList(db.goalDao().getByStatus(allStatuses()), Mappers::toDomain)) {
            reminders.cancel(g.id());
        }
        db.goalDao().deleteAll();
    }

    @Override
    public void loadDemoScenario() {
        LocalDate today = time.today();
        db.runInTransaction(() -> {
            clearAllData();
            seedWalk(today);
            seedRoadTo10k(today);
            seedReading(today);
            seedMeditation(today);
            seedArchivedCouchTo5k(today);
        });
    }

    // ---- Goals ----------------------------------------------------------------------------

    private void seedWalk(LocalDate today) {
        LocalDate start = today.minusDays(150);
        Goal goal = goal("Morning walk", "Before work, any weather.", ActivityType.WALKING, GoalUnit.KILOMETERS,
                Amount.whole(5), null, WeeklySchedule.EVERY_DAY, start, GoalColor.EMERALD, GoalIcon.WALK,
                new ReminderConfig(true, LocalTime.of(7, 0)), GoalStatus.ACTIVE, null);
        long id = insert(goal, today);
        Random random = new Random(7);
        List<ProgressEntryEntity> entries = new ArrayList<>();
        for (LocalDate d = start; d.isBefore(today); d = d.plusDays(1)) {
            boolean recentStreak = !d.isBefore(today.minusDays(23));
            double r = random.nextDouble();
            // A realistic arc: a patchy first month, then steadier habits.
            double missChance = d.isBefore(start.plusDays(30)) ? 0.18 : 0.07;
            if (recentStreak || r > missChance + 0.13) {
                long extra = random.nextDouble() < 0.28 ? 500L * (1 + random.nextInt(5)) : 0;
                entries.add(entry(id, d, Amount.whole(5), new Amount(5_000 + extra), EntryStatus.COMPLETED, null, null, false));
            } else if (r > missChance + 0.05) {
                entries.add(entry(id, d, Amount.whole(5), new Amount(1_500 + 500L * random.nextInt(6)),
                        EntryStatus.PARTIAL, null, null, false));
            } else if (r > missChance) {
                entries.add(entry(id, d, Amount.whole(5), Amount.ZERO, EntryStatus.SKIPPED, SkipReason.REST, null, false));
            }
            // else: missed (no entry)
        }
        notes(entries, "Sunrise loop by the lake.", "Felt slow but finished.", "Walked with a friend.");
        db.progressEntryDao().insertAll(entries);
    }

    /** One completion short of the 10 km milestone; today is scheduled. */
    private void seedRoadTo10k(LocalDate today) {
        ProgressionPlan plan = new ProgressionPlan(Amount.whole(3), Amount.whole(10), new Amount(500));
        DayOfWeek t = today.getDayOfWeek();
        WeeklySchedule schedule = WeeklySchedule.of(t, t.plus(2), t.plus(4), t.plus(5));
        int completionsNeeded = ProgressionEngine.totalSteps(plan) - 1; // all but the final step

        // Walk backwards over scheduled days, assigning outcomes until enough completions exist.
        Random random = new Random(11);
        List<LocalDate> days = new ArrayList<>();
        List<EntryStatus> outcomes = new ArrayList<>();
        int completions = 0;
        for (LocalDate d = today.minusDays(1); completions < completionsNeeded; d = d.minusDays(1)) {
            if (!schedule.isScheduled(d)) continue;
            double r = random.nextDouble();
            EntryStatus outcome;
            if (completions == 0 || r < 0.74) {
                outcome = EntryStatus.COMPLETED;
                completions++;
            } else if (r < 0.86) {
                outcome = EntryStatus.PARTIAL;
            } else if (r < 0.92) {
                outcome = EntryStatus.SKIPPED;
            } else {
                outcome = null; // missed
            }
            days.add(0, d);
            outcomes.add(0, outcome);
        }
        LocalDate start = days.get(0);
        Goal goal = goal("Road to 10K", "Build up to a continuous 10 km run.", ActivityType.RUNNING,
                GoalUnit.KILOMETERS, plan.startTarget(), plan, schedule, start, GoalColor.TEAL, GoalIcon.RUN,
                new ReminderConfig(true, LocalTime.of(18, 30)), GoalStatus.ACTIVE, null);
        long id = insert(goal, today);
        Amount current = replayProgression(id, plan, days, outcomes, random);
        updateTarget(id, current);
    }

    private void seedReading(LocalDate today) {
        LocalDate start = today.minusDays(100);
        Goal goal = goal("Read 20 pages", null, ActivityType.READING, GoalUnit.PAGES, Amount.whole(20), null,
                WeeklySchedule.of(DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY,
                        DayOfWeek.FRIDAY), start, GoalColor.AMBER, GoalIcon.BOOK,
                new ReminderConfig(true, LocalTime.of(21, 30)), GoalStatus.ACTIVE, null);
        long id = insert(goal, today);
        Random random = new Random(23);
        List<ProgressEntryEntity> entries = new ArrayList<>();
        for (LocalDate d = start; d.isBefore(today); d = d.plusDays(1)) {
            if (!goal.schedule().isScheduled(d)) {
                if (random.nextDouble() < 0.25) {
                    entries.add(entry(id, d, Amount.whole(20), Amount.whole(25 + random.nextInt(20)),
                            EntryStatus.COMPLETED, null, null, false));
                }
                continue;
            }
            double r = random.nextDouble();
            if (r < 0.78) {
                entries.add(entry(id, d, Amount.whole(20), Amount.whole(20 + random.nextInt(3) * 5),
                        EntryStatus.COMPLETED, null, null, false));
            } else if (r < 0.9) {
                entries.add(entry(id, d, Amount.whole(20), Amount.whole(5 + random.nextInt(12)),
                        EntryStatus.PARTIAL, null, null, false));
            }
        }
        notes(entries, "Finished part one.", "Great chapter on habits.");
        db.progressEntryDao().insertAll(entries);
    }

    private void seedMeditation(LocalDate today) {
        ProgressionPlan plan = new ProgressionPlan(Amount.whole(5), Amount.whole(30), Amount.whole(1));
        LocalDate start = today.minusDays(40);
        Goal goal = goal("Meditation 5 → 30 min", "Quiet mind before the day starts.", ActivityType.MEDITATION,
                GoalUnit.MINUTES, plan.startTarget(), plan, WeeklySchedule.EVERY_DAY, start, GoalColor.VIOLET,
                GoalIcon.MINDFUL, ReminderConfig.DEFAULT, GoalStatus.ACTIVE, null);
        long id = insert(goal, today);
        Random random = new Random(31);
        List<LocalDate> days = new ArrayList<>();
        List<EntryStatus> outcomes = new ArrayList<>();
        for (LocalDate d = start; d.isBefore(today); d = d.plusDays(1)) {
            double r = random.nextDouble();
            days.add(d);
            outcomes.add(r < 0.6 ? EntryStatus.COMPLETED : r < 0.78 ? EntryStatus.PARTIAL : r < 0.85 ? EntryStatus.SKIPPED : null);
        }
        updateTarget(id, replayProgression(id, plan, days, outcomes, random));
    }

    private void seedArchivedCouchTo5k(LocalDate today) {
        ProgressionPlan plan = new ProgressionPlan(Amount.whole(1), Amount.whole(5), new Amount(500));
        LocalDate start = today.minusDays(240);
        WeeklySchedule schedule = WeeklySchedule.of(DayOfWeek.TUESDAY, DayOfWeek.THURSDAY, DayOfWeek.SATURDAY);
        Goal goal = goal("Couch to 5K", null, ActivityType.RUNNING, GoalUnit.KILOMETERS, plan.startTarget(), plan,
                schedule, start, GoalColor.SKY, GoalIcon.RUN, ReminderConfig.DEFAULT, GoalStatus.COMPLETED, null);
        long id = insert(goal, today);
        Random random = new Random(5);
        List<LocalDate> days = new ArrayList<>();
        List<EntryStatus> outcomes = new ArrayList<>();
        int completions = 0;
        int needed = ProgressionEngine.totalSteps(plan); // including the final step
        for (LocalDate d = start; completions < needed; d = d.plusDays(1)) {
            if (!schedule.isScheduled(d)) continue;
            boolean done = random.nextDouble() < 0.8;
            if (done) completions++;
            days.add(d);
            outcomes.add(done ? EntryStatus.COMPLETED : EntryStatus.PARTIAL);
        }
        replayProgression(id, plan, days, outcomes, random);
        LocalDate end = days.get(days.size() - 1);
        MilestoneEntity m = new MilestoneEntity();
        m.goalId = id;
        m.targetMilli = plan.finalTarget().milli();
        m.achievedDate = end;
        m.celebrationState = CelebrationState.COMPLETED.key();
        m.createdAt = instant(end);
        db.milestoneDao().insert(m);
        Goal stored = Mappers.toDomain(db.goalDao().get(id));
        db.goalDao().update(Mappers.toEntity(stored.toBuilder()
                .currentTarget(plan.finalTarget()).endDate(end).build()));
    }

    // ---- Helpers ----------------------------------------------------------------------------

    /**
     * Writes entries for a progression using the real rules and returns the resulting current
     * target. A null outcome is a missed day (no entry).
     */
    private Amount replayProgression(long goalId, ProgressionPlan plan, List<LocalDate> days,
                                     List<EntryStatus> outcomes, Random random) {
        Amount current = plan.startTarget();
        List<ProgressEntryEntity> entries = new ArrayList<>();
        for (int i = 0; i < days.size(); i++) {
            EntryStatus outcome = outcomes.get(i);
            if (outcome == null) continue;
            LocalDate d = days.get(i);
            switch (outcome) {
                case COMPLETED: {
                    boolean exceed = random.nextDouble() < 0.2;
                    Amount actual = exceed ? current.plus(new Amount(500)) : current;
                    entries.add(entry(goalId, d, current, actual, EntryStatus.COMPLETED, null,
                            ProgressionEngine.level(current, plan), true));
                    current = ProgressionEngine.onCompleted(current, plan).nextTarget();
                    break;
                }
                case PARTIAL: {
                    long partial = Math.max(Amount.SCALE, current.milli() / 2 / Amount.SCALE * Amount.SCALE);
                    entries.add(entry(goalId, d, current, new Amount(partial), EntryStatus.PARTIAL, null,
                            ProgressionEngine.level(current, plan), false));
                    break;
                }
                default:
                    entries.add(entry(goalId, d, current, Amount.ZERO, EntryStatus.SKIPPED, SkipReason.REST,
                            ProgressionEngine.level(current, plan), false));
                    break;
            }
        }
        db.progressEntryDao().insertAll(entries);
        return current;
    }

    private void updateTarget(long goalId, Amount current) {
        Goal stored = Mappers.toDomain(db.goalDao().get(goalId));
        db.goalDao().update(Mappers.toEntity(stored.toBuilder().currentTarget(current).build()));
    }

    private long insert(Goal goal, LocalDate today) {
        long id = db.goalDao().insert(Mappers.toEntity(goal));
        reminders.schedule(goal.toBuilder().id(id).build());
        return id;
    }

    private Goal goal(String title, String description, ActivityType activity, GoalUnit unit, Amount target,
                      ProgressionPlan plan, WeeklySchedule schedule, LocalDate start, GoalColor color, GoalIcon icon,
                      ReminderConfig reminder, GoalStatus status, LocalDate end) {
        Instant created = instant(start);
        return new Goal.Builder()
                .uuid(UUID.randomUUID().toString())
                .title(title)
                .description(description)
                .activityType(activity)
                .trackingMode(plan == null ? TrackingMode.CONSISTENCY : TrackingMode.PROGRESSION)
                .unit(unit)
                .currentTarget(target)
                .plan(plan)
                .schedule(schedule)
                .startDate(start)
                .endDate(end)
                .reminder(reminder)
                .color(color)
                .icon(icon)
                .status(status)
                .createdAt(created)
                .updatedAt(created)
                .build();
    }

    private ProgressEntryEntity entry(long goalId, LocalDate date, Amount target, Amount actual, EntryStatus status,
                                      SkipReason reason, Integer level, boolean advanced) {
        ProgressEntryEntity e = new ProgressEntryEntity();
        e.uuid = UUID.randomUUID().toString();
        e.goalId = goalId;
        e.date = date;
        e.scheduledTargetMilli = target.milli();
        e.actualMilli = actual.milli();
        e.status = status.key();
        e.skipReason = reason == null ? null : reason.key();
        e.progressionLevel = level;
        e.advancedProgression = advanced;
        e.createdAt = instant(date).plusSeconds(19 * 3600);
        e.updatedAt = e.createdAt;
        return e;
    }

    private static void notes(List<ProgressEntryEntity> entries, String... notes) {
        for (int i = 0; i < notes.length; i++) {
            int index = entries.size() - 1 - i * 9;
            if (index >= 0) entries.get(index).note = notes[i];
        }
    }

    private Instant instant(LocalDate date) {
        return date.atStartOfDay(ZoneId.systemDefault()).toInstant();
    }

    private static List<String> allStatuses() {
        List<String> keys = new ArrayList<>();
        for (GoalStatus s : EnumSet.allOf(GoalStatus.class)) keys.add(s.key());
        return keys;
    }
}
